name: 'ZXF: Stale Issue/PR Closer'

on:
  schedule:
    - cron: '15 */1 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  actions: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  stale-pull-requests:
    name: Stale Pull Requests
    runs-on: hiero-solo-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Close Stale Pull Requests
        uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          enable-statistics: true
          delete-branch: true
          days-before-issue-stale: -1
          days-before-pr-stale: 14
          days-before-issue-close: -1
          days-before-pr-close: 14
          stale-pr-message: 'This pull request is stale because it has been open 14 days with no activity. Remove stale label or comment on this pull request; otherwise, this pull request will be closed in 14 days.'
          close-pr-message: 'This pull request was closed because it has been stalled for 14 days with no activity.'

