name: 'ZXF: Stale Issue/PR Closer'

on:
  schedule:
    - cron: '15 */1 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  actions: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  stale-pull-requests:
    name: Stale Pull Requests
    runs-on: hiero-solo-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Close Stale Pull Requests
        uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          enable-statistics: true
          delete-branch: true
          days-before-issue-stale: -1
          days-before-pr-stale: 14
          days-before-issue-close: -1
          days-before-pr-close: 14
          stale-pr-message: 'This pull request is stale because it has been open 14 days with no activity. Remove stale label or comment on this pull request; otherwise, this pull request will be closed in 14 days.'
          close-pr-message: 'This pull request was closed because it has been stalled for 14 days with no activity.'

